'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LangContext = createContext({});

const translations = {
  ru: {
    // Навигация
    catalog: 'Каталог',
    map: 'Карта',
    login: 'Войти',
    logout: 'Выйти',
    admin: 'Админ',
    cabinet: 'Кабинет',
    cart: 'Корзина',

    // Главная
    heroTitle: 'B2B маркетплейс поставщиков Кыргызстана',
    heroSubtitle: 'Находите поставщиков продуктов питания, сравнивайте цены, заказывайте оптом. Бишкек, Ош и все регионы.',
    searchPlaceholder: 'Найти товар или поставщика...',
    find: 'Найти',
    suppliers: 'Поставщиков',
    products: 'Товаров',
    cities: 'Городов',
    categories: 'Категории',
    popularProducts: 'Популярные товары',
    allProducts: 'Все товары',
    allSuppliers: 'Все поставщики',
    suppliersMap: 'Карта поставщиков',
    suppliersMapDesc: 'Найдите ближайших поставщиков на карте Кыргызстана',
    openMap: 'Открыть карту',

    // Каталог
    all: 'Все',
    productsTab: 'Товары',
    suppliersTab: 'Поставщики',
    filters: 'Фильтры',
    search: 'Поиск...',
    city: 'Город',
    allCities: 'Все города',
    price: 'Цена (сом)',
    sorting: 'Сортировка',
    newest: 'Новые',
    priceAsc: 'Цена: по возрастанию',
    priceDesc: 'Цена: по убыванию',
    byName: 'По названию',
    clearFilters: 'Сбросить фильтры',
    productsNotFound: 'Товары не найдены',
    suppliersNotFound: 'Поставщики не найдены',
    loading: 'Загрузка...',
    addToCart: 'В корзину',
    addedToCart: 'добавлено в корзину!',
    som: 'сом',

    // Категории
    confectionery: 'Кондитерка',
    drinks: 'Напитки',
    grocery: 'Бакалея',
    dairy: 'Молочные продукты',
    meat: 'Мясо и птица',
    fruits: 'Фрукты и овощи',
    frozen: 'Заморозка',
    snacks: 'Снеки',
    household: 'Бытовая химия',
    other: 'Другое',

    // Корзина
    cartEmpty: 'Корзина пуста',
    cartEmptyDesc: 'Добавьте товары из каталога, чтобы оформить заявку',
    goToCatalog: 'Перейти в каталог',
    total: 'Итого',
    items: 'шт.',
    orderForm: 'Оформить заявку',
    yourName: 'Ваше имя',
    phone: 'Телефон',
    deliveryAddress: 'Адрес доставки',
    comment: 'Комментарий',
    submitOrder: 'Отправить заявку',
    orderViaWhatsApp: 'Заказать через WhatsApp',
    supplierWillContact: 'Поставщик свяжется с вами для подтверждения заказа',
    orderSent: 'Заявка отправлена!',
    orderSentDesc: 'Поставщик свяжется с вами в ближайшее время по указанному номеру телефона.',
    backToCatalog: 'Вернуться в каталог',
    clearCart: 'Очистить корзину',
    sending: 'Отправка...',
    fillNamePhone: 'Заполните имя и телефон',

    // Поставщик
    moreDetails: 'Подробнее',
    writeWhatsApp: 'Написать в WhatsApp',
    writeTelegram: 'Написать в Telegram',
    productsCount: 'Товаров',
    backToSuppliers: 'Назад к поставщикам',
    location: 'Местоположение',
    leaveReview: 'Оставить отзыв',
    yourReview: 'Ваш отзыв...',
    send: 'Отправить',
    reviews: 'отзывов',
    noProducts: 'Товары пока не добавлены',
    order: 'Заказать',
    loginToReview: 'Войдите, чтобы оставить отзыв',
    rateFirst: 'Поставьте оценку',
    reviewAdded: 'Отзыв добавлен',
    notSpecified: 'Не указан',
    descNotSpecified: 'Описание не указано',

    // Авторизация
    registration: 'Регистрация',
    nameOrCompany: 'Ваше имя / название компании',
    password: 'Пароль',
    youAre: 'Вы:',
    buyer: 'Покупатель',
    supplier: 'Поставщик',
    noAccount: 'Нет аккаунта?',
    register: 'Зарегистрироваться',
    haveAccount: 'Уже есть аккаунт?',
    welcome: 'Добро пожаловать!',
    regSuccess: 'Регистрация прошла успешно!',
    wait: 'Подождите...',

    // Футер
    footerDesc: 'B2B маркетплейс поставщиков продуктов питания в Кыргызстане. Находите поставщиков, сравнивайте цены, заказывайте оптом.',
    navigation: 'Навигация',
    contacts: 'Контакты',
    loginReg: 'Вход / Регистрация',
    allRights: 'Все права защищены.',

    // Карта
    mapTitle: 'Карта поставщиков Кыргызстана',

    // Минимальный заказ
    minOrder: 'Мин. заказ',
    minOrderFrom: 'от',

    // Главная
    topSuppliers: 'Топ поставщики',
    topBadge: 'ТОП',
    allSuppliersBtn: 'Все поставщики',
    newOnPlatform: 'Новые на платформе',
    becomeSupplier: 'Стать поставщиком',
    becomeSupplierDesc: 'Разместите свою компанию на маркетплейсе и получайте заказы от покупателей по всему Кыргызстану',
    becomeSupplierBtn: 'Зарегистрироваться как поставщик',
    topPlacement: 'Попасть в ТОП',
    topPlacementDesc: 'Продвигайте свою компанию — попадите в раздел «Топ поставщики» на главной странице',
    topPlacementBtn: 'Узнать условия',
    byCategory: 'По категориям',

    // Промокод
    promo_code: 'Промокод',
    promo_apply: 'Применить',
    promo_applied: 'Промокод применён!',
    promo_invalid: 'Недействительный промокод',
    promo_discount: 'Скидка',
    total_with_discount: 'Итого со скидкой',

    // Реферальная программа
    referral_title: 'Пригласи друга — получи бонус!',
    referral_subtitle: 'Поделитесь кодом с друзьями. После их первой покупки вы получите бонус 500 сом!',
    referral_code: 'Ваш реферальный код',
    referral_copy: 'Копировать',
    referral_copied: 'Скопировано!',
    referral_share: 'Поделиться',
    referral_how: 'Как это работает',
    referral_step1: 'Поделитесь кодом',
    referral_step2: 'Друг регистрируется',
    referral_step3: 'Друг делает покупку',
    referral_step4: 'Получите бонус',
    referral_invited: 'Приглашено',
    referral_activated: 'Активировано',
    referral_earned: 'Заработано',

    // Заказы и уведомления
    my_orders: 'Мои заказы',
    orders_empty: 'У вас пока нет заказов',
    orders_login: 'Войдите чтобы увидеть ваши заказы',
    order_date: 'Дата заказа',
    order_items: 'Товары',
    order_total: 'Итого',
    order_details: 'Детали заказа',
    notifications: 'Уведомления',
    notif_empty: 'Нет уведомлений',
    notif_order: 'Заказ',
    notif_promo: 'Акция',
    notif_system: 'Система',
    mark_read: 'Прочитано',
    add_to_cart: 'В корзину',
    added_to_cart: 'добавлено в корзину',
    invite_friend: 'Пригласи друга',
    orders_split_desc: 'Товары разделены по поставщикам — каждому отправляется отдельная заявка',
    submit_all: 'Отправить заявку всем поставщикам',
    order_data: 'Данные для заказа',
    map_point: 'Точка доставки',
    map_find: 'На карте',
    map_hint: 'Введите адрес и нажмите «На карте» или кликните точку на карте',
    map_not_found: 'Адрес не найден. Укажите точку на карте вручную.',
    map_error: 'Ошибка поиска. Укажите точку на карте.',
    map_found: 'Адрес найден на карте!',
    print_receipt: 'Распечатать чек',
    receipt_buyer: 'Покупатель',
    receipt_phone: 'Телефон',
    receipt_address: 'Адрес доставки',
    receipt_comment: 'Комментарий',
    receipt_subtotal: 'Подытог',
    receipt_total: 'Итого',
    receipt_promo: 'Промокод',

    // Обратная связь
    feedback: 'Обратная связь',
    feedback_title: 'Обратная связь и предложения',
    feedback_submit: 'Оставить отзыв',
    feedback_thanks: 'Спасибо! Ваше обращение принято',
    feedback_type_suggestion: 'Предложение',
    feedback_type_bug: 'Ошибка',
    feedback_type_complaint: 'Жалоба',
    feedback_type_improvement: 'Улучшение',
    feedback_status_new: 'Новое',
    feedback_status_progress: 'В работе',
    feedback_status_done: 'Реализовано',
    feedback_placeholder: 'Опишите ваше предложение или проблему...',
    feedback_attach: 'Прикрепить файл',
    feedback_vote: 'Поддержать',
    feedback_sort_popular: 'По популярности',
    feedback_sort_newest: 'По новизне',
    feedback_all: 'Все',
    feedback_client: 'Клиент',
    feedback_supplier_role: 'Поставщик',
  },

  kg: {
    // Навигация
    catalog: 'Каталог',
    map: 'Карта',
    login: 'Кирүү',
    logout: 'Чыгуу',
    admin: 'Админ',
    cabinet: 'Кабинет',
    cart: 'Себет',

    // Главная
    heroTitle: 'Кыргызстандын B2B жеткирүүчүлөр маркетплейси',
    heroSubtitle: 'Азык-түлүк жеткирүүчүлөрүн табыңыз, бааларды салыштырыңыз, оптом заказ кылыңыз. Бишкек, Ош жана бардык аймактар.',
    searchPlaceholder: 'Товар же жеткирүүчү издөө...',
    find: 'Издөө',
    suppliers: 'Жеткирүүчүлөр',
    products: 'Товарлар',
    cities: 'Шаарлар',
    categories: 'Категориялар',
    popularProducts: 'Популярдуу товарлар',
    allProducts: 'Бардык товарлар',
    allSuppliers: 'Бардык жеткирүүчүлөр',
    suppliersMap: 'Жеткирүүчүлөр картасы',
    suppliersMapDesc: 'Кыргызстан картасынан жакын жеткирүүчүлөрдү табыңыз',
    openMap: 'Картаны ачуу',

    // Каталог
    all: 'Баары',
    productsTab: 'Товарлар',
    suppliersTab: 'Жеткирүүчүлөр',
    filters: 'Фильтрлер',
    search: 'Издөө...',
    city: 'Шаар',
    allCities: 'Бардык шаарлар',
    price: 'Баа (сом)',
    sorting: 'Иреттөө',
    newest: 'Жаңылар',
    priceAsc: 'Баа: өсүү боюнча',
    priceDesc: 'Баа: кемүү боюнча',
    byName: 'Аты боюнча',
    clearFilters: 'Фильтрлерди тазалоо',
    productsNotFound: 'Товарлар табылган жок',
    suppliersNotFound: 'Жеткирүүчүлөр табылган жок',
    loading: 'Жүктөлүүдө...',
    addToCart: 'Себетке',
    addedToCart: 'себетке кошулду!',
    som: 'сом',

    // Категории
    confectionery: 'Кондитердик',
    drinks: 'Суусундуктар',
    grocery: 'Бакалея',
    dairy: 'Сүт азыктары',
    meat: 'Эт жана канаттуулар',
    fruits: 'Жемиштер жана жашылчалар',
    frozen: 'Тоңдурулган',
    snacks: 'Снектер',
    household: 'Тиричилик химиясы',
    other: 'Башка',

    // Корзина
    cartEmpty: 'Себет бош',
    cartEmptyDesc: 'Заявка берүү үчүн каталогдон товарларды кошуңуз',
    goToCatalog: 'Каталогго өтүү',
    total: 'Жалпы',
    items: 'даана',
    orderForm: 'Заявка берүү',
    yourName: 'Атыңыз',
    phone: 'Телефон',
    deliveryAddress: 'Жеткирүү дареги',
    comment: 'Комментарий',
    submitOrder: 'Заявканы жөнөтүү',
    orderViaWhatsApp: 'WhatsApp аркылуу заказ',
    supplierWillContact: 'Жеткирүүчү заказды ырастоо үчүн сиз менен байланышат',
    orderSent: 'Заявка жөнөтүлдү!',
    orderSentDesc: 'Жеткирүүчү жакын арада көрсөтүлгөн телефон номери боюнча сиз менен байланышат.',
    backToCatalog: 'Каталогго кайтуу',
    clearCart: 'Себетти тазалоо',
    sending: 'Жөнөтүлүүдө...',
    fillNamePhone: 'Атыңызды жана телефонуңузду жазыңыз',

    // Поставщик
    moreDetails: 'Толугураак',
    writeWhatsApp: 'WhatsApp жазуу',
    writeTelegram: 'Telegram жазуу',
    productsCount: 'Товарлар',
    backToSuppliers: 'Жеткирүүчүлөргө кайтуу',
    location: 'Жайгашкан жери',
    leaveReview: 'Пикир калтыруу',
    yourReview: 'Сиздин пикириңиз...',
    send: 'Жөнөтүү',
    reviews: 'пикир',
    noProducts: 'Товарлар кошула элек',
    order: 'Заказ кылуу',
    loginToReview: 'Пикир калтыруу үчүн кириңиз',
    rateFirst: 'Баа коюңуз',
    reviewAdded: 'Пикир кошулду',
    notSpecified: 'Көрсөтүлгөн эмес',
    descNotSpecified: 'Сүрөттөмө көрсөтүлгөн эмес',

    // Авторизация
    registration: 'Каттоо',
    nameOrCompany: 'Атыңыз / компанияңыздын аты',
    password: 'Сыр сөз',
    youAre: 'Сиз:',
    buyer: 'Сатып алуучу',
    supplier: 'Жеткирүүчү',
    noAccount: 'Аккаунт жокпу?',
    register: 'Катталуу',
    haveAccount: 'Аккаунт барбы?',
    welcome: 'Кош келиңиз!',
    regSuccess: 'Каттоо ийгиликтүү!',
    wait: 'Күтө туруңуз...',

    // Футер
    footerDesc: 'Кыргызстандагы азык-түлүк жеткирүүчүлөрүнүн B2B маркетплейси. Жеткирүүчүлөрдү табыңыз, бааларды салыштырыңыз, оптом заказ кылыңыз.',
    navigation: 'Навигация',
    contacts: 'Байланыш',
    loginReg: 'Кирүү / Катталуу',
    allRights: 'Бардык укуктар корголгон.',

    // Карта
    mapTitle: 'Кыргызстандын жеткирүүчүлөр картасы',

    // Минимальный заказ
    minOrder: 'Мин. заказ',
    minOrderFrom: 'дан',

    // Главная
    topSuppliers: 'Топ жеткирүүчүлөр',
    topBadge: 'ТОП',
    allSuppliersBtn: 'Бардык жеткирүүчүлөр',
    newOnPlatform: 'Платформадагы жаңылар',
    becomeSupplier: 'Жеткирүүчү болуу',
    becomeSupplierDesc: 'Компанияңызды маркетплейске жайгаштырыңыз жана Кыргызстан боюнча сатып алуучулардан заказ алыңыз',
    becomeSupplierBtn: 'Жеткирүүчү катары катталуу',
    topPlacement: 'ТОПко кирүү',
    topPlacementDesc: 'Компанияңызды жылдырыңыз — башкы беттеги «Топ жеткирүүчүлөр» бөлүмүнө кириңиз',
    topPlacementBtn: 'Шарттарды билүү',
    byCategory: 'Категориялар боюнча',

    // Промокод
    promo_code: 'Промокод',
    promo_apply: 'Колдонуу',
    promo_applied: 'Промокод колдонулду!',
    promo_invalid: 'Жараксыз промокод',
    promo_discount: 'Арзандатуу',
    total_with_discount: 'Арзандатуу менен жалпы',

    // Реферальная программа
    referral_title: 'Досуңду чакыр — бонус ал!',
    referral_subtitle: 'Кодуңузду достор менен бөлүшүңүз. Алардын биринчи сатып алуусунан кийин 500 сом бонус аласыз!',
    referral_code: 'Сиздин реферал код',
    referral_copy: 'Көчүрүү',
    referral_copied: 'Көчүрүлдү!',
    referral_share: 'Бөлүшүү',
    referral_how: 'Кантип иштейт',
    referral_step1: 'Кодду бөлүшүңүз',
    referral_step2: 'Дос катталат',
    referral_step3: 'Дос сатып алат',
    referral_step4: 'Бонус алыңыз',
    referral_invited: 'Чакырылган',
    referral_activated: 'Активдештирилген',
    referral_earned: 'Табылган',

    // Заказы и уведомления
    my_orders: 'Менин буйрутмаларым',
    orders_empty: 'Сизде азырынча буйрутмалар жок',
    orders_login: 'Буйрутмаларыңызды көрүү үчүн кириңиз',
    order_date: 'Буйрутма күнү',
    order_items: 'Товарлар',
    order_total: 'Жалпы',
    order_details: 'Буйрутма чоо-жайы',
    notifications: 'Билдирүүлөр',
    notif_empty: 'Билдирүүлөр жок',
    notif_order: 'Буйрутма',
    notif_promo: 'Акция',
    notif_system: 'Система',
    mark_read: 'Окулду',
    add_to_cart: 'Себетке',
    added_to_cart: 'себетке кошулду',
    invite_friend: 'Досуңду чакыр',
    orders_split_desc: 'Товарлар жеткирүүчүлөр боюнча бөлүнгөн — ар бирине өзүнчө заявка жөнөтүлөт',
    submit_all: 'Бардык жеткирүүчүлөргө заявка жөнөтүү',
    order_data: 'Заказ үчүн маалыматтар',
    map_point: 'Жеткирүү чекити',
    map_find: 'Картадан',
    map_hint: 'Даректи жазып «Картадан» басыңыз же картадан чекитти белгилеңиз',
    map_not_found: 'Дарек табылган жок. Картадан чекитти белгилеңиз.',
    map_error: 'Издөө катасы. Картадан чекитти белгилеңиз.',
    map_found: 'Дарек картадан табылды!',
    print_receipt: 'Чекти басып чыгаруу',
    receipt_buyer: 'Сатып алуучу',
    receipt_phone: 'Телефон',
    receipt_address: 'Жеткирүү дареги',
    receipt_comment: 'Комментарий',
    receipt_subtotal: 'Аралык жыйынтык',
    receipt_total: 'Жалпы',
    receipt_promo: 'Промокод',

    // Кайтарым байланыш
    feedback: 'Кайтарым байланыш',
    feedback_title: 'Кайтарым байланыш жана сунуштар',
    feedback_submit: 'Пикир калтыруу',
    feedback_thanks: 'Рахмат! Сиздин кайрылуу кабыл алынды',
    feedback_type_suggestion: 'Сунуш',
    feedback_type_bug: 'Ката',
    feedback_type_complaint: 'Даттануу',
    feedback_type_improvement: 'Жакшыртуу',
    feedback_status_new: 'Жаңы',
    feedback_status_progress: 'Иштелүүдө',
    feedback_status_done: 'Ишке ашты',
    feedback_placeholder: 'Сунушуңузду же көйгөйүңүздү сүрөттөңүз...',
    feedback_attach: 'Файл тиркөө',
    feedback_vote: 'Колдоо',
    feedback_sort_popular: 'Популярдуулук боюнча',
    feedback_sort_newest: 'Жаңылык боюнча',
    feedback_all: 'Баары',
    feedback_client: 'Кардар',
    feedback_supplier_role: 'Жеткирүүчү',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState('ru');

  useEffect(() => {
    const saved = localStorage.getItem('lang');
    if (saved) setLang(saved);
  }, []);

  const switchLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.ru[key] || key;

  return (
    <LangContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
