name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyBj32a2048f-n8DEYwz7spYfmiEgh9A5FM
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: mama--marketplace.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: mama--marketplace
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: mama--marketplace.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "672815080455"
          NEXT_PUBLIC_FIREBASE_APP_ID: "1:672815080455:web:1fa422fc7f0f7c0c4f76a2"
          NEXT_PUBLIC_ADMIN_EMAIL: admin@gmail.com
          NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: "8626192198:AAF3gpRvvUdeOwUu3X8T3iNVvRIU_D1RZf0"
          NEXT_PUBLIC_TELEGRAM_ADMIN_CHAT_ID: "6067853905"
          NEXT_PUBLIC_GOOGLE_SHEET_URL: https://script.google.com/macros/s/AKfycbw4uQy2tANPHB5arZioFfS5WHN7dmhnoIZpm2nl2y-3IDWqmYf-pTbe_yZEM8Nif3o/exec

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - id: deployment
        uses: actions/deploy-pages@v4
